_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 71
                - 103
                - 105
                - 106
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 71
                - 103
                - 105
                - 106
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.3
            "6": 4.46.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
